/// <reference types="cypress" />
import 'cypress-file-upload';

it('Login sucess test' , function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
    cy.get('input[name="password"]').type('sfgbc#super@dmin')
    cy.get('#remember').click()
    

    

    
});



it('login Failier test', function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('input[name="email"]').type('webmasterrrr@semienfgbc.org')
    cy.get('input[name="password"]').type('sfgbcddd#super@dmin')
    cy.get('.login100-form-btn').click()
    // cy.get('.alert').should('have.text' , "*** CAUTION !!! \n The provided credentials DO NOT MATCH our records. \nPlease try again...")
    
});

it('forget password', function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('.txt2 > label').click()
    cy.location().should((loc) => {
        expect(loc.pathname.toString()).to.contain('/forgetpassword');
      });
    
})
it('login with empty fileds ' , function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('.login100-form-btn').click()
    
})

it('login with email and no password', function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('input[name="email"]').type('webmasterrrr@semienfgbc.org')
    cy.get('.login100-form-btn').click()
})

it('Login and logout back', function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
    cy.get('input[name="password"]').type('sfgbc#super@dmin')
    cy.get('#remember').click()
    cy.get('.login100-form-btn').click()
    cy.get('.dropdown-toggle').click()
    cy.get('.dropdown-menu').contains('Sign Out').click()

});

it('Dashbord test', function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
    cy.get('input[name="password"]').type('sfgbc#super@dmin')
    cy.get('.login100-form-btn').click()
    cy.get(':nth-child(3) > .col-lg-8 > .card > .card-header > .card-title').should('have.text', 'New Members')
    cy.get(':nth-child(3) > .col-lg-4 > .card > .bg-white > .card-title').should('have.text', 'Fellowship Leaders')
    // cy.get(':nth-child(2) > :nth-child(1) > .dash-widget > .dash-widget-info > .widget-title1').should('have.text', 'Members')
    cy.get('.card-block > .table-responsive > .table > tbody > tr > :nth-child(1)').should('have.text', "Member's Full Name")
    cy.get('.card-block > .table-responsive > .table > tbody > tr > :nth-child(2)').should('have.text', "Gender")
    cy.get('.card-block > .table-responsive > .table > tbody > tr > :nth-child(3)').should('have.text', 'Civil Status')
    cy.get('.card-block > .table-responsive > .table > tbody > tr > :nth-child(4)').should('have.text', "Action")
    cy.get(':nth-child(5) > .col-lg-8 > .card > .card-header > .card-title').should('have.text', 'Upcoming Appointments')
    cy.get('.card-body > .table-responsive > .table > tbody > tr > :nth-child(1)').should('have.text', "Member's Full Name")
    cy.get('.card-body > .table-responsive > .table > tbody > tr > :nth-child(2)').should('have.text', 'Gender')
    cy.get('.card-body > .table-responsive > .table > tbody > tr > :nth-child(3)').should('have.text', "Civil Status")
    cy.get('.card-body > .table-responsive > .table > tbody > tr > :nth-child(4)').should('have.text', 'Action')
    cy.get('.card-title > strong').should('have.text', 'Service Sector Leaders')
    cy.contains('View all Members').click()
    cy.location().should((loc) => {
        expect(loc.pathname.toString()).to.contain('/members');
      });
    cy.go('back')
    cy.contains('View all Fellowships').click()
    cy.location().should((loc) => {
        expect(loc.pathname.toString()).to.contain('/fellowships');
      });
    cy.go('back')
    cy.scrollTo(0,500)
    cy.get(':nth-child(5) > .col-lg-4 > .card > :nth-child(2) > .btn').click()
    cy.location().should((loc)=>{
        expect(loc.pathname.toString()).to.contain('/servicesectors')
    });
    cy.go('back')
    // cy.contains('View all Appointments').click()
    // cy.location().should((loc) => {
    //     expect(loc.pathname.toString()).to.contain('/appointments');
    //   });
    cy.go('back')
    cy.get(':nth-child(5) > .col-lg-4 > .card > :nth-child(2) > .btn').click()
    cy.go('back')
    cy.get('.dropdown-toggle > strong > span').click()
    cy.get('.dropdown-menu > [href="#"]').click()
    cy.location().should((loc) => {
        expect(loc.pathname.toString()).to.contain('/myprofile');
      });
    
    
}) ;
it('Add memebers data ', function(){
    cy.visit('https://mrms.semienfgbc.org/')
    cy.scrollTo(0, 500)
    cy.get('.login100-form-btn').click()
    cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
    cy.get('input[name="password"]').type('sfgbc#super@dmin')
    cy.get('.login100-form-btn').click()
     cy.contains('View all Members').click()
    cy.location().should((loc) => {
        expect(loc.pathname.toString()).to.contain('/members');
      });
    cy.get('.col-3 > .btn').click()
    cy.location().should((loc) => {
        expect(loc.pathname.toString()).to.contain('/create');
      });
      
      cy.get('.page-title').should('have.text', 'የአዲስ አባል መረጃ መመዝገቢያ | New Member Data Registration')
      cy.get(':nth-child(3) > .card-title').should('have.text', 'የግል መረጃ | Personal Information')
      cy.get('input[type=file]').attachFile("person.png")
      cy.get('#imagePreview').should("be.visible")

      cy.get('.select2-selection__rendered').contains('Select Appillation').click()
      cy.get('.select2-results__option').contains('Ato').click()
      cy.get('#txtFirstName').type('franol')
      cy.get('.profile-basic > .row > :nth-child(3) > .form-group > .form-control').type('Geleta')
      cy.get('.profile-basic > .row > :nth-child(4) > .form-group > .form-control').type('Gemechu')
      cy.get('.select2-selection__rendered').contains('Select Gender').click()
      cy.get('#MemberBirthDatePicker').click()
      cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
      cy.get('[title="ዓመቱን ቀይር"]').select('1989')
      cy.get('tbody').contains('27').click()
      cy.get('.select2-selection__rendered').contains('Select Gender').click()
      cy.get('.select2-results__option').contains('Male').click()
      cy.get('.select2-selection__rendered').contains('Select Civil Status').click()
      cy.get('.select2-results__option').contains('Never Married').click()
      cy.get(':nth-child(4) > .card-title').should('have.text', 'የመኖሪያ አድራሻ መረጃ | Residential Address Information')
      cy.get(':nth-child(4) > .row > :nth-child(3) > .form-group > .form-control').type('Addis Ababa')
      cy.get(':nth-child(4) > .row > :nth-child(4) > .form-group > .form-control').type('aytawekem')
      cy.get(':nth-child(4) > .row > :nth-child(5) > .form-group > .form-control').type('semen')
      cy.get(':nth-child(4) > .row > :nth-child(7) > .form-group > .form-control').type('08')
      cy.get(':nth-child(4) > .row > :nth-child(8) > .form-group > .form-control').type('01')
      cy.get(':nth-child(9) > .form-group > .form-control').type('Addis gebeya/ total')
      cy.get(':nth-child(10) > .form-group > .form-control').type('New')
      cy.get(':nth-child(11) > .form-group > .form-control').type('belaye zeleke')
      cy.get(':nth-child(12) > .form-group > .cal-icon > .form-control').type('0922492122')
      cy.get(':nth-child(13) > .form-group > .cal-icon > .form-control').type('0989059295')
      cy.get(':nth-child(14) > .form-group > .cal-icon > .form-control').type('0111273683')
      cy.get(':nth-child(15) > .form-group > .cal-icon > .form-control').type('0111111111')
      cy.get(':nth-child(16) > .form-group > .form-control').type('999')
      cy.get(':nth-child(17) > .form-group > .form-control').type('Franolgeleta5@gmail.com')
      cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .focus-label').should('have.text', 'የአድራሻ ማስታወሻ | Address Remarks')
      cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .form-control').type('Some testing address')
      cy.get(':nth-child(5) > .card-title').should('have.text','የአባልነት መረጃ | Membership Information')
      cy.get('#rdoHowBecameNewBeliever').click()
      cy.get('#BelievedDatePicker').click()
      cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
      cy.get('[title="ዓመቱን ቀይር"]').select('1989')
      cy.get('tbody').contains('27').click()
      cy.get('#BaptizedDatePicker').click()
      cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
      cy.get('[title="ዓመቱን ቀይር"]').select('1989')
      cy.get('tbody').contains('27').click()
      cy.get('#memPreviousReligion > .form-group > .form-control').type('meserte kirstos')
      cy.get('#memWhoThought > .form-group > .form-control').type('pastor some one')
      cy.get('#MembershipDatePicker').click()
      cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
      cy.get('[title="ዓመቱን ቀይር"]').select('1989')
      cy.get('tbody').contains('27').click()
      cy.get('#memMembershipRemarks > .form-group > .focus-label').should('have.text','አባልነትን የተመለከተ ማስታወሻ | Membership Remarks')
      cy.get('#memMembershipRemarks > .form-group > .form-control').type('some comment test')
      cy.get(':nth-child(6) > .card-title').should('have.text','ተጨማሪ መረጃ | Additional Information')
      cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .focus-label').should('have.text', 'የአካል ጉዳት (ካለ) | Disability (If Any)')
      cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .form-control').type('no')
      cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .focus-label').should('have.text', "አባሉን የተመለከተ ማስታወሻ | Personal Member's Remarks")
      cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .form-control').type('no')
      cy.get('.text-center > .btn').click()
    //   cy.get('#select2-cmbAppillation-st-container').click()
    //   cy.get(':nth-child(3) > [data-layer="Padding"]').select('Ato')
    //   cy.get('.select2-selection__rendered').select('Ato')

      // cy.get("").attachFile("person.png")
    // cy.fixture('person.png').as('logo')
    // cy.get('.fileupload').then(function($input){
    //     return Cypress.Blob.base64StringToBlob(this.logo, 'image/png')
    //     .then((blob) => {
    //         $input.fileupload('add', {files: blob})
    //     })
    // })
      
})


it('Add memebers data with photo missing', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
   cy.contains('View all Members').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/members');
    });
  cy.get('.col-3 > .btn').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/create');
    });
    
    cy.get('.page-title').should('have.text', 'የአዲስ አባል መረጃ መመዝገቢያ | New Member Data Registration')
    cy.get(':nth-child(3) > .card-title').should('have.text', 'የግል መረጃ | Personal Information')
    

    cy.get('.select2-selection__rendered').contains('Select Appillation').click()
    cy.get('.select2-results__option').contains('Ato').click()
    cy.get('#txtFirstName').type('franol')
    cy.get('.profile-basic > .row > :nth-child(3) > .form-group > .form-control').type('Geleta')
    cy.get('.profile-basic > .row > :nth-child(4) > .form-group > .form-control').type('Gemechu')
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('#MemberBirthDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('.select2-results__option').contains('Male').click()
    cy.get('.select2-selection__rendered').contains('Select Civil Status').click()
    cy.get('.select2-results__option').contains('Never Married').click()
    cy.get(':nth-child(4) > .card-title').should('have.text', 'የመኖሪያ አድራሻ መረጃ | Residential Address Information')
    cy.get(':nth-child(4) > .row > :nth-child(3) > .form-group > .form-control').type('Addis Ababa')
    cy.get(':nth-child(4) > .row > :nth-child(4) > .form-group > .form-control').type('aytawekem')
    cy.get(':nth-child(4) > .row > :nth-child(5) > .form-group > .form-control').type('semen')
    cy.get(':nth-child(4) > .row > :nth-child(7) > .form-group > .form-control').type('08')
    cy.get(':nth-child(4) > .row > :nth-child(8) > .form-group > .form-control').type('01')
    cy.get(':nth-child(9) > .form-group > .form-control').type('Addis gebeya/ total')
    cy.get(':nth-child(10) > .form-group > .form-control').type('New')
    cy.get(':nth-child(11) > .form-group > .form-control').type('belaye zeleke')
    cy.get(':nth-child(12) > .form-group > .cal-icon > .form-control').type('0922492122')
    cy.get(':nth-child(13) > .form-group > .cal-icon > .form-control').type('0989059295')
    cy.get(':nth-child(14) > .form-group > .cal-icon > .form-control').type('0111273683')
    cy.get(':nth-child(15) > .form-group > .cal-icon > .form-control').type('0111111111')
    cy.get(':nth-child(16) > .form-group > .form-control').type('999')
    cy.get(':nth-child(17) > .form-group > .form-control').type('Franolgeleta5@gmail.com')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .focus-label').should('have.text', 'የአድራሻ ማስታወሻ | Address Remarks')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .form-control').type('Some testing address')
    cy.get(':nth-child(5) > .card-title').should('have.text','የአባልነት መረጃ | Membership Information')
    cy.get('#rdoHowBecameNewBeliever').click()
    cy.get('#BelievedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#BaptizedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memPreviousReligion > .form-group > .form-control').type('meserte kirstos')
    cy.get('#memWhoThought > .form-group > .form-control').type('pastor some one')
    cy.get('#MembershipDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memMembershipRemarks > .form-group > .focus-label').should('have.text','አባልነትን የተመለከተ ማስታወሻ | Membership Remarks')
    cy.get('#memMembershipRemarks > .form-group > .form-control').type('some comment test')
    cy.get(':nth-child(6) > .card-title').should('have.text','ተጨማሪ መረጃ | Additional Information')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .focus-label').should('have.text', 'የአካል ጉዳት (ካለ) | Disability (If Any)')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .form-control').type('no')
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .focus-label').should('have.text', "አባሉን የተመለከተ ማስታወሻ | Personal Member's Remarks")
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .form-control').type('no')
    cy.get('.text-center > .btn').click()
  //   cy.get('#select2-cmbAppillation-st-container').click()
  //   cy.get(':nth-child(3) > [data-layer="Padding"]').select('Ato')
  //   cy.get('.select2-selection__rendered').select('Ato')

    // cy.get("").attachFile("person.png")
  // cy.fixture('person.png').as('logo')
  // cy.get('.fileupload').then(function($input){
  //     return Cypress.Blob.base64StringToBlob(this.logo, 'image/png')
  //     .then((blob) => {
  //         $input.fileupload('add', {files: blob})
  //     })
  // })
    
})

it('Add memebers with out names ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
   cy.contains('View all Members').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/members');
    });
  cy.get('.col-3 > .btn').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/create');
    });
    
    cy.get('.page-title').should('have.text', 'የአዲስ አባል መረጃ መመዝገቢያ | New Member Data Registration')
    cy.get(':nth-child(3) > .card-title').should('have.text', 'የግል መረጃ | Personal Information')
    cy.get('input[type=file]').attachFile("person.png")
    cy.get('#imagePreview').should("be.visible")

    cy.get('.select2-selection__rendered').contains('Select Appillation').click()
    cy.get('.select2-results__option').contains('Ato').click()
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('#MemberBirthDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('.select2-results__option').contains('Male').click()
    cy.get('.select2-selection__rendered').contains('Select Civil Status').click()
    cy.get('.select2-results__option').contains('Never Married').click()
    cy.get(':nth-child(4) > .card-title').should('have.text', 'የመኖሪያ አድራሻ መረጃ | Residential Address Information')
    cy.get(':nth-child(4) > .row > :nth-child(3) > .form-group > .form-control').type('Addis Ababa')
    cy.get(':nth-child(4) > .row > :nth-child(4) > .form-group > .form-control').type('aytawekem')
    cy.get(':nth-child(4) > .row > :nth-child(5) > .form-group > .form-control').type('semen')
    cy.get(':nth-child(4) > .row > :nth-child(7) > .form-group > .form-control').type('08')
    cy.get(':nth-child(4) > .row > :nth-child(8) > .form-group > .form-control').type('01')
    cy.get(':nth-child(9) > .form-group > .form-control').type('Addis gebeya/ total')
    cy.get(':nth-child(10) > .form-group > .form-control').type('New')
    cy.get(':nth-child(11) > .form-group > .form-control').type('belaye zeleke')
    cy.get(':nth-child(12) > .form-group > .cal-icon > .form-control').type('0922492122')
    cy.get(':nth-child(13) > .form-group > .cal-icon > .form-control').type('0989059295')
    cy.get(':nth-child(14) > .form-group > .cal-icon > .form-control').type('0111273683')
    cy.get(':nth-child(15) > .form-group > .cal-icon > .form-control').type('0111111111')
    cy.get(':nth-child(16) > .form-group > .form-control').type('999')
    cy.get(':nth-child(17) > .form-group > .form-control').type('Franolgeleta5@gmail.com')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .focus-label').should('have.text', 'የአድራሻ ማስታወሻ | Address Remarks')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .form-control').type('Some testing address')
    cy.get(':nth-child(5) > .card-title').should('have.text','የአባልነት መረጃ | Membership Information')
    cy.get('#rdoHowBecameNewBeliever').click()
    cy.get('#BelievedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#BaptizedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memPreviousReligion > .form-group > .form-control').type('meserte kirstos')
    cy.get('#memWhoThought > .form-group > .form-control').type('pastor some one')
    cy.get('#MembershipDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memMembershipRemarks > .form-group > .focus-label').should('have.text','አባልነትን የተመለከተ ማስታወሻ | Membership Remarks')
    cy.get('#memMembershipRemarks > .form-group > .form-control').type('some comment test')
    cy.get(':nth-child(6) > .card-title').should('have.text','ተጨማሪ መረጃ | Additional Information')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .focus-label').should('have.text', 'የአካል ጉዳት (ካለ) | Disability (If Any)')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .form-control').type('no')
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .focus-label').should('have.text', "አባሉን የተመለከተ ማስታወሻ | Personal Member's Remarks")
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .form-control').type('no')
    cy.get('.text-center > .btn').click()
  //   cy.get('#select2-cmbAppillation-st-container').click()
  //   cy.get(':nth-child(3) > [data-layer="Padding"]').select('Ato')
  //   cy.get('.select2-selection__rendered').select('Ato')

    // cy.get("").attachFile("person.png")
  // cy.fixture('person.png').as('logo')
  // cy.get('.fileupload').then(function($input){
  //     return Cypress.Blob.base64StringToBlob(this.logo, 'image/png')
  //     .then((blob) => {
  //         $input.fileupload('add', {files: blob})
  //     })
  // })
    
})

it('Add memebers data with middle and last name missing ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
   cy.contains('View all Members').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/members');
    });
  cy.get('.col-3 > .btn').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/create');
    });
    
    cy.get('.page-title').should('have.text', 'የአዲስ አባል መረጃ መመዝገቢያ | New Member Data Registration')
    cy.get(':nth-child(3) > .card-title').should('have.text', 'የግል መረጃ | Personal Information')
    cy.get('input[type=file]').attachFile("person.png")
    cy.get('#imagePreview').should("be.visible")

    cy.get('.select2-selection__rendered').contains('Select Appillation').click()
    cy.get('.select2-results__option').contains('Ato').click()
    cy.get('#txtFirstName').type('franol')
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('#MemberBirthDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('.select2-results__option').contains('Male').click()
    cy.get('.select2-selection__rendered').contains('Select Civil Status').click()
    cy.get('.select2-results__option').contains('Never Married').click()
    cy.get(':nth-child(4) > .card-title').should('have.text', 'የመኖሪያ አድራሻ መረጃ | Residential Address Information')
    cy.get(':nth-child(4) > .row > :nth-child(3) > .form-group > .form-control').type('Addis Ababa')
    cy.get(':nth-child(4) > .row > :nth-child(4) > .form-group > .form-control').type('aytawekem')
    cy.get(':nth-child(4) > .row > :nth-child(5) > .form-group > .form-control').type('semen')
    cy.get(':nth-child(4) > .row > :nth-child(7) > .form-group > .form-control').type('08')
    cy.get(':nth-child(4) > .row > :nth-child(8) > .form-group > .form-control').type('01')
    cy.get(':nth-child(9) > .form-group > .form-control').type('Addis gebeya/ total')
    cy.get(':nth-child(10) > .form-group > .form-control').type('New')
    cy.get(':nth-child(11) > .form-group > .form-control').type('belaye zeleke')
    cy.get(':nth-child(12) > .form-group > .cal-icon > .form-control').type('0922492122')
    cy.get(':nth-child(13) > .form-group > .cal-icon > .form-control').type('0989059295')
    cy.get(':nth-child(14) > .form-group > .cal-icon > .form-control').type('0111273683')
    cy.get(':nth-child(15) > .form-group > .cal-icon > .form-control').type('0111111111')
    cy.get(':nth-child(16) > .form-group > .form-control').type('999')
    cy.get(':nth-child(17) > .form-group > .form-control').type('Franolgeleta5@gmail.com')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .focus-label').should('have.text', 'የአድራሻ ማስታወሻ | Address Remarks')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .form-control').type('Some testing address')
    cy.get(':nth-child(5) > .card-title').should('have.text','የአባልነት መረጃ | Membership Information')
    cy.get('#rdoHowBecameNewBeliever').click()
    cy.get('#BelievedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#BaptizedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memPreviousReligion > .form-group > .form-control').type('meserte kirstos')
    cy.get('#memWhoThought > .form-group > .form-control').type('pastor some one')
    cy.get('#MembershipDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memMembershipRemarks > .form-group > .focus-label').should('have.text','አባልነትን የተመለከተ ማስታወሻ | Membership Remarks')
    cy.get('#memMembershipRemarks > .form-group > .form-control').type('some comment test')
    cy.get(':nth-child(6) > .card-title').should('have.text','ተጨማሪ መረጃ | Additional Information')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .focus-label').should('have.text', 'የአካል ጉዳት (ካለ) | Disability (If Any)')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .form-control').type('no')
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .focus-label').should('have.text', "አባሉን የተመለከተ ማስታወሻ | Personal Member's Remarks")
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .form-control').type('no')
    cy.get('.text-center > .btn').click()
  //   cy.get('#select2-cmbAppillation-st-container').click()
  //   cy.get(':nth-child(3) > [data-layer="Padding"]').select('Ato')
  //   cy.get('.select2-selection__rendered').select('Ato')

    // cy.get("").attachFile("person.png")
  // cy.fixture('person.png').as('logo')
  // cy.get('.fileupload').then(function($input){
  //     return Cypress.Blob.base64StringToBlob(this.logo, 'image/png')
  //     .then((blob) => {
  //         $input.fileupload('add', {files: blob})
  //     })
  // })
    
})

it('Add memebers data with date of birth missing  ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
   cy.contains('View all Members').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/members');
    });
  cy.get('.col-3 > .btn').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/create');
    });
    
    cy.get('.page-title').should('have.text', 'የአዲስ አባል መረጃ መመዝገቢያ | New Member Data Registration')
    cy.get(':nth-child(3) > .card-title').should('have.text', 'የግል መረጃ | Personal Information')
    cy.get('input[type=file]').attachFile("person.png")
    cy.get('#imagePreview').should("be.visible")

    cy.get('.select2-selection__rendered').contains('Select Appillation').click()
    cy.get('.select2-results__option').contains('Ato').click()
    cy.get('#txtFirstName').type('franol')
    cy.get('.profile-basic > .row > :nth-child(3) > .form-group > .form-control').type('Geleta')
    cy.get('.profile-basic > .row > :nth-child(4) > .form-group > .form-control').type('Gemechu')
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('.select2-results__option').contains('Male').click()
    cy.get('.select2-selection__rendered').contains('Select Civil Status').click()
    cy.get('.select2-results__option').contains('Never Married').click()
    cy.get(':nth-child(4) > .card-title').should('have.text', 'የመኖሪያ አድራሻ መረጃ | Residential Address Information')
    cy.get(':nth-child(4) > .row > :nth-child(3) > .form-group > .form-control').type('Addis Ababa')
    cy.get(':nth-child(4) > .row > :nth-child(4) > .form-group > .form-control').type('aytawekem')
    cy.get(':nth-child(4) > .row > :nth-child(5) > .form-group > .form-control').type('semen')
    cy.get(':nth-child(4) > .row > :nth-child(7) > .form-group > .form-control').type('08')
    cy.get(':nth-child(4) > .row > :nth-child(8) > .form-group > .form-control').type('01')
    cy.get(':nth-child(9) > .form-group > .form-control').type('Addis gebeya/ total')
    cy.get(':nth-child(10) > .form-group > .form-control').type('New')
    cy.get(':nth-child(11) > .form-group > .form-control').type('belaye zeleke')
    cy.get(':nth-child(12) > .form-group > .cal-icon > .form-control').type('0922492122')
    cy.get(':nth-child(13) > .form-group > .cal-icon > .form-control').type('0989059295')
    cy.get(':nth-child(14) > .form-group > .cal-icon > .form-control').type('0111273683')
    cy.get(':nth-child(15) > .form-group > .cal-icon > .form-control').type('0111111111')
    cy.get(':nth-child(16) > .form-group > .form-control').type('999')
    cy.get(':nth-child(17) > .form-group > .form-control').type('Franolgeleta5@gmail.com')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .focus-label').should('have.text', 'የአድራሻ ማስታወሻ | Address Remarks')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .form-control').type('Some testing address')
    cy.get(':nth-child(5) > .card-title').should('have.text','የአባልነት መረጃ | Membership Information')
    cy.get('#rdoHowBecameNewBeliever').click()
    cy.get('#BelievedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#BaptizedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memPreviousReligion > .form-group > .form-control').type('meserte kirstos')
    cy.get('#memWhoThought > .form-group > .form-control').type('pastor some one')
    cy.get('#MembershipDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memMembershipRemarks > .form-group > .focus-label').should('have.text','አባልነትን የተመለከተ ማስታወሻ | Membership Remarks')
    cy.get('#memMembershipRemarks > .form-group > .form-control').type('some comment test')
    cy.get(':nth-child(6) > .card-title').should('have.text','ተጨማሪ መረጃ | Additional Information')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .focus-label').should('have.text', 'የአካል ጉዳት (ካለ) | Disability (If Any)')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .form-control').type('no')
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .focus-label').should('have.text', "አባሉን የተመለከተ ማስታወሻ | Personal Member's Remarks")
    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .form-control').type('no')
    cy.get('.text-center > .btn').click()
  //   cy.get('#select2-cmbAppillation-st-container').click()
  //   cy.get(':nth-child(3) > [data-layer="Padding"]').select('Ato')
  //   cy.get('.select2-selection__rendered').select('Ato')

    // cy.get("").attachFile("person.png")
  // cy.fixture('person.png').as('logo')
  // cy.get('.fileupload').then(function($input){
  //     return Cypress.Blob.base64StringToBlob(this.logo, 'image/png')
  //     .then((blob) => {
  //         $input.fileupload('add', {files: blob})
  //     })
  // })
    
})

it('Add memebers data with only mandatory fileds  ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
   cy.contains('View all Members').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/members');
    });
  cy.get('.col-3 > .btn').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/create');
    });
    
    cy.get('.page-title').should('have.text', 'የአዲስ አባል መረጃ መመዝገቢያ | New Member Data Registration')
    cy.get(':nth-child(3) > .card-title').should('have.text', 'የግል መረጃ | Personal Information')
    cy.get('input[type=file]').attachFile("person.png")
    cy.get('#imagePreview').should("be.visible")

    cy.get('.select2-selection__rendered').contains('Select Appillation').click()
    cy.get('.select2-results__option').contains('Ato').click()
    cy.get('#txtFirstName').type('franol')
    cy.get('.profile-basic > .row > :nth-child(3) > .form-group > .form-control').type('Geleta')
    cy.get('.profile-basic > .row > :nth-child(4) > .form-group > .form-control').type('Gemechu')
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('#MemberBirthDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('.select2-selection__rendered').contains('Select Gender').click()
    cy.get('.select2-results__option').contains('Male').click()
    cy.get('.select2-selection__rendered').contains('Select Civil Status').click()
    cy.get('.select2-results__option').contains('Never Married').click()
    cy.get(':nth-child(4) > .card-title').should('have.text', 'የመኖሪያ አድራሻ መረጃ | Residential Address Information')
    cy.get(':nth-child(4) > .row > :nth-child(3) > .form-group > .form-control').type('Addis Ababa')
    cy.get(':nth-child(4) > .row > :nth-child(7) > .form-group > .form-control').type('08')
    cy.get(':nth-child(11) > .form-group > .form-control').type('belaye zeleke')

    cy.get(':nth-child(12) > .form-group > .cal-icon > .form-control').type('0922492122')
    cy.get(':nth-child(4) > .row > .col-md-12 > .form-group > .focus-label').should('have.text', 'የአድራሻ ማስታወሻ | Address Remarks')
    cy.get(':nth-child(5) > .card-title').should('have.text','የአባልነት መረጃ | Membership Information')
    cy.get('#rdoHowBecameNewBeliever').click()
    cy.get('#BelievedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#BaptizedDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memPreviousReligion > .form-group > .form-control').type('meserte kirstos')
    cy.get('#memWhoThought > .form-group > .form-control').type('pastor some one')
    cy.get('#MembershipDatePicker').click()
    cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
    cy.get('[title="ዓመቱን ቀይር"]').select('1989')
    cy.get('tbody').contains('27').click()
    cy.get('#memMembershipRemarks > .form-group > .focus-label').should('have.text','አባልነትን የተመለከተ ማስታወሻ | Membership Remarks')
    
    cy.get(':nth-child(6) > .card-title').should('have.text','ተጨማሪ መረጃ | Additional Information')
    cy.get(':nth-child(6) > .row > :nth-child(1) > .form-group > .focus-label').should('have.text', 'የአካል ጉዳት (ካለ) | Disability (If Any)')

    cy.get(':nth-child(6) > .row > :nth-child(2) > .form-group > .focus-label').should('have.text', "አባሉን የተመለከተ ማስታወሻ | Personal Member's Remarks")

    cy.get('.text-center > .btn').click()
  //   cy.get('#select2-cmbAppillation-st-container').click()
  //   cy.get(':nth-child(3) > [data-layer="Padding"]').select('Ato')
  //   cy.get('.select2-selection__rendered').select('Ato')

    // cy.get("").attachFile("person.png")
  // cy.fixture('person.png').as('logo')
  // cy.get('.fileupload').then(function($input){
  //     return Cypress.Blob.base64StringToBlob(this.logo, 'image/png')
  //     .then((blob) => {
  //         $input.fileupload('add', {files: blob})
  //     })
  // })
    
})



it('members page testing  ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
   cy.contains('View all Members').click()
  cy.location().should((loc) => {
      expect(loc.pathname.toString()).to.contain('/members');
    });
  cy.get('.page-title').should('have.text',"የአባላት ዝርዝር | Members' Cataloge")
  cy.get('#iSearchMember').type('franol')
  cy.get('.col-md-4 > .btn').click()
  cy.get('[aria-label="Member ID: activate to sort column ascending"]').should('have.text', "Member ID")
  cy.get('.wrap').should('have.text', 'Photo || Full Name')
  cy.get('[style="min-width: 25px; width: 50.9062px;"]').should('have.text', 'Gender')
  cy.get('[aria-label="Status: activate to sort column ascending"]').should('have.text', 'Status')
})

it('Fellow ship data testing', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(1) > :nth-child(6) > [href="#"] > :nth-child(2)').click()
  cy.get(':nth-child(6) > ul > .active > a').click()
  cy.get('.page-title').should('have.text', "የህብረቶች ዝርዝር | Fellowships' Cataloge")
  cy.get('.col-3 > .btn > strong').click()
  cy.location().should((loc) => {
    expect(loc.pathname.toString()).to.contain('/create');
  });
  cy.go('back')
  cy.get('.form-control').type('test')
  cy.get('.col-md-2 > .btn > strong').click()
  cy.get('.odd > .sorting_1 > .dropdown > .btn-outline-danger').click()
  cy.get('.dropdown-menu > [href="https://mrms.semienfgbc.org/fellowships/show/2"]').click()
  cy.get(':nth-child(3) > .form-group > .form-control').type('testtt')
  cy.get(':nth-child(2) > .btn').click()
  cy.go('back')
  cy.get(':nth-child(3) > .btn > strong').click()
  cy.get('.odd > .sorting_1 > .dropdown > .btn-outline-danger').click()
  cy.get('.dropdown-menu > [href="https://mrms.semienfgbc.org/fellowships/edit/2"]').click()
  cy.go('back')
  cy.get('.odd > .sorting_1 > .dropdown > .btn-outline-danger').click()
  cy.get('.dropdown-menu > [href="https://mrms.semienfgbc.org/fellowships/remove/2"]').click()
  cy.go('back')

})


it('Add Fellow ship data testing', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(1) > :nth-child(6) > [href="#"] > :nth-child(2)').click()
  cy.get(':nth-child(6) > ul > :nth-child(4) > a').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Type').click()
  cy.get('.select2-results__option').contains('Youth Service Fellowship').click()
  cy.get(':nth-child(2) > .col-md-7 > .form-control').type('hello hibret')
  cy.get('.select2-selection__rendered').contains('Select Church Local Zone').click()
  cy.get('.select2-results__option').contains('Addisu Gebeya').click()
  cy.get(':nth-child(4) > .col-md-7 > .form-control').type('yebalebet sem')
  cy.get(':nth-child(5) > .col-md-7 > .form-control').type('name')
  cy.get('#FellowshipFoundedDatePicker').click()
  cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
  cy.get('[title="ዓመቱን ቀይር"]').select('1989')
  cy.get('tbody').contains('27').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Day Held On').click()
  cy.get('.select2-results__option').contains('Tuesday').click()
  cy.get('[name="timeStartingTime"]').click()
  cy.get('[name="timeStartingTime"]').type('12:33')
  cy.get('[name="timeEndingTime"]').click()
  cy.get('[name="timeEndingTime"]').type('01:21')
  cy.get('#rdoFellowshipStatus_Active').click()
  cy.get('div.col-md-12 > .form-control').type('this is mastawesha testing')
  cy.get('.text-center > .btn').click()

})

it('Add Fellow ship with out fellowship type', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(1) > :nth-child(6) > [href="#"] > :nth-child(2)').click()
  cy.get(':nth-child(6) > ul > :nth-child(4) > a').click()
  cy.get(':nth-child(2) > .col-md-7 > .form-control').type('hello hibret')
  cy.get('.select2-selection__rendered').contains('Select Church Local Zone').click()
  cy.get('.select2-results__option').contains('Addisu Gebeya').click()
  cy.get(':nth-child(4) > .col-md-7 > .form-control').type('yebalebet sem')
  cy.get(':nth-child(5) > .col-md-7 > .form-control').type('name')
  cy.get('#FellowshipFoundedDatePicker').click()
  cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
  cy.get('[title="ዓመቱን ቀይር"]').select('1989')
  cy.get('tbody').contains('27').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Day Held On').click()
  cy.get('.select2-results__option').contains('Tuesday').click()
  cy.get('[name="timeStartingTime"]').click()
  cy.get('[name="timeStartingTime"]').type('12:33')
  cy.get('[name="timeEndingTime"]').click()
  cy.get('[name="timeEndingTime"]').type('01:21')
  cy.get('#rdoFellowshipStatus_Active').click()
  cy.get('div.col-md-12 > .form-control').type('this is mastawesha testing')
  cy.get('.text-center > .btn').click()

})

it('Add Fellow ship with out felowship label', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(1) > :nth-child(6) > [href="#"] > :nth-child(2)').click()
  cy.get(':nth-child(6) > ul > :nth-child(4) > a').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Type').click()
  cy.get('.select2-results__option').contains('Youth Service Fellowship').click()
  cy.get('.select2-selection__rendered').contains('Select Church Local Zone').click()
  cy.get('.select2-results__option').contains('Addisu Gebeya').click()
  cy.get(':nth-child(4) > .col-md-7 > .form-control').type('yebalebet sem')
  cy.get(':nth-child(5) > .col-md-7 > .form-control').type('name')
  cy.get('#FellowshipFoundedDatePicker').click()
  cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
  cy.get('[title="ዓመቱን ቀይር"]').select('1989')
  cy.get('tbody').contains('27').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Day Held On').click()
  cy.get('.select2-results__option').contains('Tuesday').click()
  cy.get('[name="timeStartingTime"]').click()
  cy.get('[name="timeStartingTime"]').type('12:33')
  cy.get('[name="timeEndingTime"]').click()
  cy.get('[name="timeEndingTime"]').type('01:21')
  cy.get('#rdoFellowshipStatus_Active').click()
  cy.get('div.col-md-12 > .form-control').type('this is mastawesha testing')
  cy.get('.text-center > .btn').click()

})

it('Add Fellow ship data with out fellowship remarks', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(1) > :nth-child(6) > [href="#"] > :nth-child(2)').click()
  cy.get(':nth-child(6) > ul > :nth-child(4) > a').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Type').click()
  cy.get('.select2-results__option').contains('Youth Service Fellowship').click()
  cy.get(':nth-child(2) > .col-md-7 > .form-control').type('hello hibret')
  cy.get('.select2-selection__rendered').contains('Select Church Local Zone').click()
  cy.get('.select2-results__option').contains('Addisu Gebeya').click()
  cy.get(':nth-child(4) > .col-md-7 > .form-control').type('yebalebet sem')
  cy.get(':nth-child(5) > .col-md-7 > .form-control').type('name')
  cy.get('#FellowshipFoundedDatePicker').click()
  cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
  cy.get('[title="ዓመቱን ቀይር"]').select('1989')
  cy.get('tbody').contains('27').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Day Held On').click()
  cy.get('.select2-results__option').contains('Tuesday').click()
  cy.get('[name="timeStartingTime"]').click()
  cy.get('[name="timeStartingTime"]').type('12:33')
  cy.get('[name="timeEndingTime"]').click()
  cy.get('[name="timeEndingTime"]').type('01:21')
  cy.get('#rdoFellowshipStatus_Active').click()
  cy.get('.text-center > .btn').click()

})

it('Add Fellow ship data with exsisting same data ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(1) > :nth-child(6) > [href="#"] > :nth-child(2)').click()
  cy.get(':nth-child(6) > ul > :nth-child(4) > a').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Type').click()
  cy.get('.select2-results__option').contains('Youth Service Fellowship').click()
  cy.get(':nth-child(2) > .col-md-7 > .form-control').type('hello hibret')
  cy.get('.select2-selection__rendered').contains('Select Church Local Zone').click()
  cy.get('.select2-results__option').contains('Addisu Gebeya').click()
  cy.get(':nth-child(4) > .col-md-7 > .form-control').type('yebalebet sem')
  cy.get(':nth-child(5) > .col-md-7 > .form-control').type('name')
  cy.get('#FellowshipFoundedDatePicker').click()
  cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
  cy.get('[title="ዓመቱን ቀይር"]').select('1989')
  cy.get('tbody').contains('27').click()
  cy.get('.select2-selection__rendered').contains('Select Fellowship Day Held On').click()
  cy.get('.select2-results__option').contains('Tuesday').click()
  cy.get('[name="timeStartingTime"]').click()
  cy.get('[name="timeStartingTime"]').type('12:33')
  cy.get('[name="timeEndingTime"]').click()
  cy.get('[name="timeEndingTime"]').type('01:21')
  cy.get('#rdoFellowshipStatus_Active').click()
  cy.get('div.col-md-12 > .form-control').type('this is mastawesha testing')
  cy.get('.text-center > .btn').click()

})

it('Add Fellow ship data with empty  filds  ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(1) > :nth-child(6) > [href="#"] > :nth-child(2)').click()
  cy.get(':nth-child(6) > ul > :nth-child(4) > a').click()
  
  cy.get('.text-center > .btn').click()

})


it('Add sector  data with exsisting same data ', function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(7) > [href="#"]').click()
  cy.get(':nth-child(7) > ul > .active > a').click()
  cy.get('.page-title').should('have.text', "የአገልግሎት ዘርፍ ዝርዝር | Service Sectors' Cataloge")
  cy.get('.col-4 > .btn').click()
  cy.get('.select2-selection__rendered').contains('Select Service Sector Type').click()
  cy.get('.select2-results__option').contains('Evangelism and Testimonials Service').click()
  cy.get('#SectorEstabilishedDatePicker').click()
  cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
  cy.get('[title="ዓመቱን ቀይር"]').select('1989')
  cy.get('tbody').contains('27').click()
  cy.get('.richText-editor').type('some testing text ')
  cy.get('#rdoSectorStatus_Active').click()
  cy.get('[name="txaServiceSectorRemark"]').type('some thing')
  cy.get('.text-center > .btn').click()

  

})


it("Add Sector data with out  Service Sector's Remarks ", function(){
  cy.visit('https://mrms.semienfgbc.org/')
  cy.scrollTo(0, 500)
  cy.get('.login100-form-btn').click()
  cy.get('input[name="email"]').type('webmaster@semienfgbc.org')
  cy.get('input[name="password"]').type('sfgbc#super@dmin')
  cy.get('.login100-form-btn').click()
  cy.get('#toggle_btn > .fa').click()
  cy.get(':nth-child(7) > [href="#"]').click()
  cy.get(':nth-child(7) > ul > .active > a').click()
  cy.get('.page-title').should('have.text', "የአገልግሎት ዘርፍ ዝርዝር | Service Sectors' Cataloge")
  cy.get('.col-4 > .btn').click()
  cy.get('.select2-selection__rendered').contains('Select Service Sector Type').click()
  cy.get('.select2-results__option').contains('Evangelism and Testimonials Service').click()
  cy.get('#SectorEstabilishedDatePicker').click()
  cy.get('[title="ወሩን ቀይር"]').select('መስከረም')
  cy.get('[title="ዓመቱን ቀይር"]').select('1989')
  cy.get('tbody').contains('27').click()
  cy.get('.richText-editor').type('some testing text ')
  cy.get('#rdoSectorStatus_Active').click()
  cy.get('.text-center > .btn').click()

  

})
